// const RapidAPIKey = import.meta.env.VITE_RapidAPIKey;

const englishWordsArray = [
    "apple",
    "beach",
    "chair",
    "drink",
    "earth",
    "faith",
    "glass",
    "horse",
    "image",
    "fruit",
    "dance",
    "candy",
    "drama",
    "cloud",
    "diner",
    "eagle",
    "flame",
    "grape",
    "happy",
    "igloo",
    "jolly",
    "koala",
    "lemon",
    "music",
    "noble",
    "ocean",
    "piano",
    "queen",
    "rider",
    "sunny",
    "table",
    "vivid",
    "xerox",
    "yacht",
    "zebra",
    "fairy",
    "magic",
    "swirl",
    "dream",
    "smile",
    "joker",
    "heart",
    "honey",
    "wrist",
    "robot",
    "space",
    "tower",
    "swift",
    "clock",
    "peace",
    "frost",
    "crane",
    "stork",
    "trick",
    "tiger",
    "lucky",
    "lunar",
    "chill",
    "brave",
    "tulip",
    "scent",
    "smoke",
    "fable",
    "treat",
    "wings",
    "guide",
    "prize",
    "oasis",
    "jewel",
    "glory",
    "spear",
    "grain",
    "voice",
    "truth",
    "glove",
    "novel",
    "blade",
    "honor",
    "trend",
    "unity",
];

const germanWordsArray = [
    "Apfel",
    "Wolke",
    "Hilfe",
    "Fluss",
    "Sonne",
    "Zebra",
    "Fisch",
    "Liebe",
    "Schlaf",
    "Reise",
    "Rente",
    "Kabel",
    "Kugel",
    "Hafen",
    "Eiche",
    "Motor",
    "Brief",
    "Seife",
    "Hunde",
    "Milch",
    "Venus",
    "Seide",
    "Ernte",
    "Wolle",
    "Decke",
    "Blume",
    "Tasse",
    "Wagen",
    "Nacht",
    "Pferd",
    "Tisch",
    "Spiel",
    "Kreis",
    "Messe",
    "Radio",
    "Kopie",
    "Karte",
    "Kiste",
    "Vogel",
    "Mauer",
    "Taste",
    "Seite",
    "Frage",
    "Licht",
    "Blick",
    "Trost",
    "Zunge",
    "Krone",
    "Wache",
    "Traum",
    "Stern",
    "Boden",
    "Fuchs",
    "Kamel",
    "Panda",
    "Abend",
    "Weide",
    "Wiese",
    "Wurst",
    "Dreck",
    "Tritt",
    "Feder",
    "Welle",
    "Turbo",
    "Lampe",
    "Komet",
    "Pfote",
    "Qualm",
    "Kette",
    "Walze",
    "Worte",
    "Tiger",
    "Wunde",
    "Pfand",
    "Fabel",
    "Anker",
    "Tante",
    "Schuh",
    "Nudel",
    "Feuer",
    "Salat",
    "Recht",
    "Brust",
    "Leben",
    "Pflug",
    "Laser",
    "Tinte",
    "Faden",
    "Kreuz",
    "Kiosk",
    "Glanz",
    "Hertz",
    "Brand",
    "Schal",
    "Clown",
    "Stift",
    "Quark",
    "Prinz",
    "Ruder",
    "Flirt",
    "Sorge",
    "Knabe",
    "Saite",
    "Teich",
];

interface fetchProps {
    lang: string;
}
export const fetchNewWords = async ({ lang }: fetchProps) => {
    if (lang === "en") {
        const randomWord =
            englishWordsArray[
                Math.floor(Math.random() * englishWordsArray.length)
            ];
        return randomWord;
    } else if (lang === "de") {
        const randomWord =
            germanWordsArray[
                Math.floor(Math.random() * germanWordsArray.length)
            ];
        return randomWord;
    }
};

// export const fetchNewWords = async () => {
//     const url = "https://random-words5.p.rapidapi.com/getRandom?wordLength=5";
//     const options = {
//         method: "GET",
//         headers: {
//             "X-RapidAPI-Key": RapidAPIKey,
//             "X-RapidAPI-Host": "random-words5.p.rapidapi.com",
//         },
//     };
//     try {
//         const response = await fetch(url, options);
//         const result = await response.text();
//         return result;
//     } catch (error) {
//         console.error(error);
//     }
// };
